In [1]:
import numpy as np
import pandas as pd

In [2]:
pwd

'/home/lauvindra/Linear Regression/Dataset/CCPP'

In [3]:
dataset_path = './dataset_csv.csv'
learning_rate = 0.00001
num_epoch = 10000
test_training_ratio = 0.2
batch_size = 1000

In [4]:
df = pd.read_csv(dataset_path)#Read the dataset
df.head()

AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [5]:
#For iloc we will get a tuple with [rows,columns]
sum_X = df.iloc[:, :-1].values #To sort all the independant data
sum_y = df.iloc[:, -1].values #To sort all the dependant data

In [6]:
#This is like the c in a linear equation
b = np.ones((sum_X.shape[0], sum_X.shape[1]+1)) #We add another column 
b[:,1:] = sum_X #take all the values for rows and from index 1 in columns
sum_X = b #reassign to make it easier to read
print(sum_X[:5])

[[1.00000e+00 8.34000e+00 4.07700e+01 1.01084e+03 9.00100e+01]
 [1.00000e+00 2.36400e+01 5.84900e+01 1.01140e+03 7.42000e+01]
 [1.00000e+00 2.97400e+01 5.69000e+01 1.00715e+03 4.19100e+01]
 [1.00000e+00 1.90700e+01 4.96900e+01 1.00722e+03 7.67900e+01]
 [1.00000e+00 1.18000e+01 4.06600e+01 1.01713e+03 9.72000e+01]]


In [7]:
theta = np.random.rand(sum_X.shape[1]) #randomly assign a floating value to each independant data column

In [8]:
theta


array([0.69240606, 0.66960445, 0.45403194, 0.43345163, 0.64124311])

In [9]:
#For us to verify the accuracy we store 20% of the dataset,
#We have 5 columns and 9568 columns
num_of_testing_example = int(test_training_ratio*(sum_X.shape[0])) #0.2*9568 = 1913.6
num_of_training_example = sum_X.shape[0] - num_of_testing_example # 9568 - 1913.6 = 7654.4

X_train = sum_X[:num_of_training_example]
y_train = sum_y[:num_of_training_example]

X_test = sum_X[num_of_training_example:]
y_test = sum_y[num_of_training_example:]

In [10]:
one = X_train.shape[0]
two =  sum_X.shape[0]
print(one, two)

7655 9568


In [11]:
#For testing
def testing_with_MSE():
    diff = X_test.dot(theta) - y_test #h(θ) -y
    
    loss = (1/(2*X_test.shape[0]))*(diff.dot(diff))
    
    print("The testing loss wwith MSE:", loss)
    
def testing_with_R2():
    diff = X_test.dot(theta) - y_test 
    
    
testing_with_MSE()

The testing loss wwith MSE: 2715.487241375952


In [12]:
#to turn our training
for epoch in range(num_epoch):
    
    Y_diff = X_train.dot(theta) - y_train 
    
    loss = (1/(2*sum_X.shape[0]))*(Y_diff.dot(Y_diff)) #calculate loss function
    
    #Train by batch 1000
    for first_index in range(0, sum_X.shape[0],batch_size):
        last_index = first_index + batch_size #To assign last value of the index
        last_index = None if last_index > X_train.shape[0] else last_index #if last index is > total number of data points, it will set to none
        
        y_hat = X_train[first_index:last_index].dot(theta)#predicted output
        y_hat_diff = y_hat - y_train[first_index:last_index]
        
        m = 1/y_train.shape[0] #number of data points
        
        for i in range(theta.shape[0]):
            x_j = X_train[first_index:last_index,i]#get x_j vector for the specified batch size
            
            par_der = m*y_hat_diff.dot(X_train[first_index:last_index,i]) 
            
            theta[i] = theta[i] - learning_rate*par_der
    
    if epoch % 1000 == 0:
        print("Epoch :", epoch)
        print("Loss :",loss)
        

Epoch : 0
Loss : 2206.666928439711
Epoch : 1000
Loss : 29.85939476952275
Epoch : 2000
Loss : 19.960052799406743
Epoch : 3000
Loss : 17.93649475371581
Epoch : 4000
Loss : 16.648727796502296
Epoch : 5000
Loss : 15.600155099391449
Epoch : 6000
Loss : 14.726658302554402
Epoch : 7000
Loss : 13.997720050286885
Epoch : 8000
Loss : 13.38933938084402
Epoch : 9000
Loss : 12.881569408058231


In [13]:
print(theta)

[ 0.69243622 -0.98250991 -0.59645054  0.49846015  0.00554135]


In [15]:
testing_with_MSE()

The testing loss wwith MSE: 15.185355992118131
